package cse.SUSTC.ParkingApp;

import android.app.Application;
//import android.content.Context;

import com.uuzuche.lib_zxing.activity.ZXingLibrary;

import org.xutils.x;

import java.util.HashMap;
import java.util.Map;

/**
 * This class will run basic config of app and store for some static variable
 */
public class MyApplication extends Application  {

    /**
     * The URL of server.
     */
//    public final static String URL = "https://ffaapi.herokuapp.com";
    public final static String URL = "http://47.113.221.224:8012";
//    public final static String URL = "http://192.168.0.105:8012";
    /**
     * The key of session value.
     */
    public final static String SESSION_NAME = "JSESSIONID";
    /**
     * The error massage generated by app.
     */
    protected static final Map<String, String> ERR_MSG;
    static
    {
        Map<String, String> tmp = new HashMap<>();
        tmp.put("log1", "Username doesn't match password");
        tmp.put("log2", "Username doesn't exit");
        tmp.put("reg1", "Username has already exit");
        tmp.put("reg2", "Please fill all blank");
        tmp.put("reg3", "Please input a correct information");
        ERR_MSG = tmp;
    }

    /**
     * The log in code received from server.
     */
    private static String loginCode = "";
    /**
     * The register code received from server.
     */
    private static String registerCode = "";
    /**
     * A boolean value to indicate the log in state.
     */
    private static boolean loginState = false;
    /**
     * The session value.
     */
    private static String session = "";
    @Override
    public void onCreate() {
        super.onCreate();
        x.Ext.init(this);
        x.Ext.setDebug(true);
        ZXingLibrary.initDisplayOpinion(this);

    }

    /**
     * set Login Code
     * @param loginCode login status code
     */
    public static void setLoginCode(String loginCode) {
        MyApplication.loginCode = loginCode;
    }

    /**
     * set Register Code
     *
     * @param registerCode  register status code
     */
    public static void setRegisterCode(String registerCode) {
        MyApplication.registerCode = registerCode;
    }

    /**
     * @return loginCode
     */
    public static String getLoginCode() {
        return loginCode;
    }

    /**
     * @return registerCode
     */
    public static String getRegisterCode() {
        return registerCode;
    }



    /**
     * @return loginState
     */
    public static boolean isLoginState() {
        return loginState;
    }

    /**
     * @param loginState login State
     */
    public static void setLoginState(boolean loginState) {
        MyApplication.loginState = loginState;
    }

    /**
     * @return session
     */
    public static String getSession() {
        return session;
    }

    /**
     * @param session session
     */
    public static void setSession(String session) {
        MyApplication.session = session;
    }

}